var pages_js = new Array();
 pages_js = {

// File Name:Index.htm
Index:	{
	t_noFrame               	:		"Please upgrade to a version 4 or higher browser so that you can use this setup tool.",
	js_info_end	:"js_info_end"
},

// File Name:MenuRpm.htm
MenuRpm:	{
	js_info_end	:"js_info_end"
},

// File Name:AdvScrRpm.htm
ntw_adv_scr:	{
	t_adv_scr               	:		"Advanced Security",
	t_ping                  	:		"Ping",
	t_ping_wan              	:		"Ping from WAN",
	t_interval              	:		"Packets Statistics Interval (5 ~ 60):",
	t_seconds               	:		"&nbsp;Seconds",
	t_dos_protection        	:		"DoS Protection:",
	t_disable               	:		"Disable",
	t_enable                	:		"Enable",
	t_en_icmp               	:		"Enable ICMP-FLOOD Attack Filtering",
	t_icmp_thrd             	:		"ICMP-FLOOD Packets Threshold (5 ~ 3600):",
	t_pkts0                 	:		"&nbsp;Packets/s ",
	t_en_udp                	:		"Enable UDP-FLOOD Filtering",
	t_udp_thrd              	:		"UDP-FLOOD Packets Threshold (5 ~ 3600):",
	t_pkts1                 	:		"&nbsp;Packets/s",
	t_en_tcp                	:		"Enable TCP-SYN-FLOOD Attack Filtering",
	t_tcp_thrd              	:		"TCP-SYN-FLOOD Packets Threshold (5 ~ 3600):",
	t_pkts2                 	:		"&nbsp;Packets/s",
	t_ingore_ping           	:		"&nbsp;Ignore Ping Packet From WAN Port",
	t_forbid_ping           	:		"&nbsp;Forbid Ping Packet From LAN Port",
	js_bad_icmp_thrd        	:		"Bad ICMP-FLOOD Packets threshold, please input another number!(5-3600)",	
	js_bad_udp_thrd         	:		"Bad UDP-FLOOD Packets threshold, please input another number!(5-3600)",	
	js_bad_tcp_thrd         	:		"Bad TCP-FLOOD Packets threshold, please input another number!(5-3600)",	
	js_info_end	:"js_info_end"
},

// File Name:AssignedIpAddrListRpm.htm
ntw_assigned_ip_addr_list:	{
	t_title                 	:		"DHCP Clients List",
	t_id                    	:		"ID",
	t_client_name           	:		"Client Name",
	t_mac_addr              	:		"MAC Address",
	t_assigned_ip           	:		"Assigned IP",
	t_lease_time            	:		"Lease Time",
	t_none                  	:		"none",
	t_permanent             	:		"Permanent",
	t_list_none             	:		"No attached client currently.",
	js_info_end	:"js_info_end"
},

// File Name:AuthError.htm
AuthError:	{
	js_info_end	:"js_info_end"
},

// File Name:BakNRestoreRpm.htm
ntw_bakn_restore:	{
	t_title                 	:		"Backup & Restore",
	t_backup                	:		"Backup:",
	t_file                  	:		"File:",
	js_choose_file          	:		"Please choose a file for loading!",	
	js_mksure_load          	:		"Are you sure to load?",	
	js_info_end	:"js_info_end"
},

// File Name:BPACfgRpm.htm
ntw_bpa_cfg:	{
	t_dyna                  	:		"Dynamic IP",
	t_stat                  	:		"Static IP",
	t_pppoe                 	:		"PPPoE/Russia PPPoE",
	t_802dy                 	:		"802.1X + Dynamic IP",
	t_802st                 	:		"802.1X + Static IP",
	t_bpa                   	:		"BigPond Cable",
	t_l2tp                  	:		"L2TP/Russia L2TP",
	t_pptp                  	:		"PPTP/Russia PPTP",
	t_dualaccess            	:		"Dual Access/Russia PPPoE",
	t_dhpcplus              	:		"DHCP+",
	t_title                 	:		"WAN",
	t_wan_port              	:		"WAN Port:",
	t_wan_con_type          	:		"WAN Connection Type:",
	t_usrname               	:		"User Name:",
	t_pwd                   	:		"Password:",
	t_auth_srv              	:		"Auth Server:",
	t_auth_domain           	:		"Auth Domain:",
	t_egress_bdwth          	:		"Egress Bandwidth:",
	t_option0               	:		" Kbps (Optional)",
	t_ingress_bdwth         	:		"Ingress Bandwidth:",
	t_option1               	:		" Kbps (Optional)",
	t_mtu_size              	:		"MTU Size (in bytes):",
	t_mtu_deault            	:		"(The default is 1500. Do not change it unless necessary.)",
	t_con_on_demand         	:		"Connect on Demand",
	t_max_idle_time0        	:		"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Max Idle Time: &nbsp; ",
	t_minutes0              	:		"minutes (0 means remaining active all the time.)",
	t_con_auto              	:		"Connect Automatically",
	t_con_manually          	:		"Connect Manually",
	t_max_idle_time1        	:		"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Max Idle Time: &nbsp; ",
	t_minutes1              	:		"minutes (0 means remaining active all the time.)",
	t_disconnected          	:		"Disconnected!",
	t_connected             	:		"Connected!",
	t_Connecting            	:		"Connecting...",
	js_bad_waittime         	:		"Bad max idle time,please input another number!\n",	
	js_mksure_bpa_change    	:		"BPA connection type is changed, so the old\n\nconnection will be disconnected. Continue?",	
	js_bad_mtu              	:		"Bad MTU,please input another number!\n(576~1500,the default is 1500)",	
	js_info_end	:"js_info_end"
},

// File Name:ChangeLoginPwdRpm.htm
ntw_change_login_pwd:	{
	t_title                 	:		"Password",
	t_old_user_name         	:		"Old User Name:",
	t_old_pwd               	:		"Old Password:",
	t_new_user_name         	:		"New User Name:",
	t_new_pwd               	:		"New Password:",
	t_conf_new_pwd          	:		"Confirm New Password:",
	js_illegal_input        	:		"The input value contain illegal character, please input another one!",	
	js_illegal_input2       	:		"The input value contains illegal characters, please input another one! (The illegal character is the character except for alphabet, number, '-' and '_'.",	
	js_req_field            	:		"Required field cannot be left blank!",	
	js_bad_confirm_pwd      	:		"The confirm password must accord with the new password!",	
	js_info_end	:"js_info_end"
},

// File Name:CmxDdnsRpm.htm
ntw_cmx_ddns:	{
	t_title                 	:		"DDNS",
	t_provider              	:		"Service Provider:",
	t_register              	:		"Go to register...",
	t_wan_port              	:		"WAN Port:",
	t_domainname0           	:		"Domain Name:",
	t_domainname1           	:		"Domain Name:",
	t_domainname2           	:		"Domain Name:",
	t_domainname3           	:		"Domain Name:",
	t_domainname4           	:		"Domain Name:",
	t_usrname               	:		"User Name:",
	t_pwd                   	:		"Password:",
	t_en_ddns               	:		"&nbsp;Enable DDNS",
	t_con_status            	:		"Connection Status:",
	t_not_launch            	:		"DDNS not launching!",
	t_connecting            	:		"Connecting...",
	t_succeeded             	:		"Succeeded!",
	t_pwd_error             	:		"User or Password error!",
	t_domain_error          	:		"Domain Name error",
	js_info_end	:"js_info_end"
},

// File Name:confUploadErrorRpm.htm
ntw_conf_upload_err:	{
	t_title                 	:		"Error",
	t_config_err            	:		"Config file error:",
	t_command               	:		"command",
	t_err_type              	:		"error type",
	js_info_end	:"js_info_end"
},

// File Name:DateTimeCfgRpm.htm
ntw_date_time_cfg:	{
	t_title                 	:		"Time Settings",
	t_time_zone             	:		"Time Zone:",
	t_timezone0             	:		"(GMT-12:00) Eniwetok,Kwajalein",
	t_timezone60             	:		"(GMT-11:00) Midway Island,Samoa",
	t_timezone120             	:		"(GMT-10:00) Hawaii",
	t_timezone180             	:		"(GMT-09:00) Alaska",
	t_timezone240             	:		"(GMT-08:00) Pacific Time",
	t_timezone300             	:		"(GMT-07:00) Mountain Time (US Canada)",
	t_timezone360             	:		"(GMT-06:00) Central Time (US Canada)",
	t_timezone420             	:		"(GMT-05:00) Eastern Time (US Canada)",
	t_timezone480             	:		"(GMT-04:00) Atlantic Time (Canada)",
	t_timezone510            	:		"(GMT-03:30) Newfoundland",
	t_timezone540				:		"(GMT-03:00) Brasilia, Buenos Aires",
	t_timezone600            	:		"(GMT-02:00) Mid-Atlantic",
	t_timezone660            	:		"(GMT-01:00) Azores, Cape Verde Is",
	t_timezone720            	:		"(GMT) Greenwich Mean Time, Dublin, London",
	t_timezone780            	:		"(GMT+01:00) Berlin, Stockholm, Rome, Bern, Brussels",
	t_timezone840            	:		"(GMT+02:00) Athens, Helsinki, Eastern Europe, Israel",
	t_timezone900            	:		"(GMT+03:00) Baghdad, Kuwait, Nairobi, Riyadh, Moscow",
	t_timezone930				:		"(GMT+03:30) Teheran",
	t_timezone960            	:		"(GMT+04:00) Abu Dhabi, Muscat, Kazan, Volgograd",
	t_timezone990				:		"(GMT+04:30) Kabul",
	t_timezone1020            	:		"(GMT+05:00) Islamabad, Karachi, Ekaterinburg",
	t_timezone1050				:		"(GMT+05:30) Madras, Calcutta, Bombay, New Delhi",
	t_timezone1065				:		"(GMT+05:45) Katmandu",
	t_timezone1080            	:		"(GMT+06:00) Alma-Ata, Dhaka",
	t_timezone1110				:		"(GMT+06:30) Rangoon",
	t_timezone1140            	:		"(GMT+07:00) Bangkok, Jakarta, Hanoi",
	t_timezone1200            	:		"(GMT+08:00) Beijing, Hong Kong, Perth, Singapore",
	t_timezone1260            	:		"(GMT+09:00) Tokyo, Osaka, Sapporo, Seoul, Yakutsk",
	t_timezone1290				:		"(GMT+09:30) Adelaide",
	t_timezone1320            	:		"(GMT+10:00) Brisbane, Canberra, Melbourne, Sydney",
	t_timezone1380            	:		"(GMT+11:00) Magadan, Solomon Is., New Caledonia",
	t_timezone1440            	:		"(GMT+12:00) Fiji, Kamchatka, Auckland",
	t_timezone1500            	:		"(GMT+13:00) Nukualofa",
	t_date                  	:		"Date:",
	t_mdy                   	:		"(MM/DD/YY)",
	t_time                  	:		"Time:",
	t_hms                   	:		"(HH/MM/SS)",
	t_ntp_srva              	:		"Primary NTP Server:",
	t_ntp_srvb              	:		"Secondary NTP Server:",
	t_optional					:		"(Optional)",
	t_enDaylightSaving			:		"Enable Daylight Saving",
	t_start		               	:		"Start:",
	t_month_january				:		"Jan.",
	t_month_february			:		"Feb.",
	t_month_march				:		"Mar.",
	t_month_april				:		"Apr.",
	t_month_may					:		"May",
	t_month_june				:		"Jun",
	t_month_july				:		"Jul.",
	t_month_august				:		"Aug",
	t_month_september			:		"Sep",
	t_month_october				:		"Oct.",
	t_month_november			:		"Nov.",
	t_month_december			:		"Dec",
	t_count_first				:		"1st",
	t_count_second				:		"2nd",
	t_count_third				:		"3rd",
	t_count_fourth				:		"4th",
	t_count_fifth				:		"5th",
	t_week_sunday				:		"Sun.  ",
	t_week_monday				:		"Mon.  ",
	t_week_tuesday				:		"Tues. ",
	t_week_wednesday			:		"Wed.  ",
	t_week_thursday				:		"Thurs.",
	t_week_friday				:		"Friday",
	t_week_saturday				:		"Sat.  ",
	t_hour_am1					:		"1am",
	t_hour_am2					:		"2am",
	t_hour_am3					:		"3am",
	t_hour_am4					:		"4am",
	t_hour_am5					:		"5am",
	t_hour_am6					:		"6am",
	t_hour_am7					:		"7am",
	t_hour_am8					:		"8am",
	t_hour_am9					:		"9am",
	t_hour_am10					:		"10am",
	t_hour_am11					:		"11am",
	t_hour_pm12					:		"12pm",
	t_hour_pm1					:		"1pm",
	t_hour_pm2					:		"2pm",
	t_hour_pm3					:		"3pm",
	t_hour_pm4					:		"4pm",
	t_hour_pm5					:		"5pm",
	t_hour_pm6					:		"6pm",
	t_hour_pm7					:		"7pm",
	t_hour_pm8					:		"8pm",
	t_hour_pm9					:		"9pm",
	t_hour_pm10					:		"10pm",
	t_hour_pm11					:		"11pm",
	t_hour_am12					:		"12am",
	t_note_first				:		"Note:Click the \"GET GMT\" to update the time from the internet with the pre-defined servers",
	t_note_last					:		"or entering the customized server(IP Address or Domain Name) in the above frames.",
	js_input_ip             	:		"Please input IP address or domain name!",	
	js_input_time           	:		"Please input a time!",	
	js_bad_year             	:		"Wrong format of year, please input another one(1970-2037)!",
	js_bad_month            	:		"Wrong format of month, please input another one(1-12)!",	
	js_bad_day              	:		"Wrong format of day, please input another one(1-31)!",	
	js_bad_hour             	:		"Wrong format of hour, please input another one(0-23)!",	
	js_bad_minute           	:		"Wrong format of minute, please input another one(0-59)!",	
	js_bad_secd             	:		"Wrong format of second, please input another one(0-59)!",	
	js_bad_dstdate				:		"Daylight date set is invalid, start day must be earlier than end day!",
	js_info_end	:"js_info_end"
},

// File Name:DMZRpm.htm
ntw_dmz:	{
	t_title                 	:		"DMZ",
	t_status                	:		"Current DMZ Status:",
	t_enable                	:		"Enable",
	t_disable               	:		"Disable",
	t_dmz_ip                	:		"DMZ Host IP Address:",
	js_bad_dmz_ip           	:		"The DMZ Host IP Address is invalid, please input again!",	
	js_info_end	:"js_info_end"
},

// File Name:DomainFilterRpm.htm
ntw_domain_filter:	{
	t_title                 	:		"Domain Filtering",
	t_fw_set                	:		"Firewall Settings (You can change them on Firewall page)",
	t_en_fw                 	:		"Enable Firewall:",
	t_en_domain_flt         	:		"Enable Domain Filtering:",
	t_effect_time           	:		"Effective time",
	t_domain_name           	:		"Domain Name",
	t_status                	:		"Status",
	t_modify                	:		"Modify",
	t_enable                	:		"Enabled",
	t_disable               	:		"Disabled",
	t_modify1               	:		"Modify",
	t_delete                	:		"Delete",
	t_enabled               	:		"Enabled",
	t_disabled              	:		"Disabled",
	js_no_entry             	:		"No entry exists in the table!",	
	js_mksure_delete        	:		"Are you sure to delete all entries?",	
	js_info_end	:"js_info_end"
},

// File Name:DomainFilterAdvRpm.htm
ntw_domain_filter_adv:	{
	t_title                 	:		"Add or Modify a Domain Filtering Entry",
	t_effect_time           	:		"Effective Time:",
	t_domain_name           	:		"Domain Name:",
	t_status                	:		"Status:",
	t_disable               	:		"Disabled",
	t_enable                	:		"Enabled",
	js_bad_start_time       	:		"Bad start time (only 4 numbers), please input another number!",	
	js_bad_end_time         	:		"Bad end time (only 4 numbers), please input another number!",	
	js_info_end	:"js_info_end"
},

// File Name:DynDdnsRpm.htm
ntw_dyn_ddns:	{
	t_title                 	:		"DDNS",
	t_srv_provider          	:		"Service Provider:",
	t_register              	:		"Go to register...",
	t_wan_port              	:		"WAN Port:",
	t_usr_name              	:		"User Name:",
	t_pwd                   	:		"Password:",
	t_domain_name           	:		"Domain Name:",
	t_en_ddns               	:		"&nbsp;Enable DDNS",
	t_con_status            	:		"Connection Status:",
	t_not_launch            	:		"DDNS not launching!",
	t_connecting            	:		"Connecting...",
	t_succeeded             	:		"Succeeded!",
	t_pwd_error             	:		"User or Password error!",
	t_domain_error          	:		"Domain Name error",
	js_info_end	:"js_info_end"
},

// File Name:DiagnosticIframeRpm.htm
DiagnosticIframeRpm:	{
	js_info_end	:"js_info_end"
},

// File Name:DiagnosticRpm.htm
diagnostic_cfg:	{
	t_title                 	:		"Diagnostic Tools",
	t_diag_conf             	:		"Diagnostic Configuration",
	t_cho_mode              	:		"Choose Mode:",
	t_ping                  	:		"Ping&nbsp;&nbsp;",
	t_tracert               	:		"Tracert",
	t_ip_domain             	:		"IP Address/ Domain Name:",
	t_num_pings             	:		"Number of Pings:",
	t_ping_size             	:		"Ping Size:",
	t_ping_timeout          	:		"Ping Timeout:",
	t_mill_sec              	:		"(100-2000 Milliseconds)",
	t_tracert_hops          	:		"Tracert Hops:",
	t_diag_hops             	:		"Diagnostic Results",
	js_addr_null            	:		"Please input IP address/Domain name first!",	
	js_ping_num_error       	:		"Number of Pings must be a value between 1~100!",	
	js_pkt_size_error       	:		"Package Size must be a value between 4~500!",	
	js_timeout_error        	:		"Timeout must be a value between 100~2000!",	
	js_tracert_hop_error    	:		"Tracert Hops must be a value between 1~30!",	
	js_info_end	:"js_info_end"
},

// File Name:errorPage.htm
errorPage:	{
	t_title                 	:		"Error",
	t_err_prompt            	:		"Error occurred, please try again.",
	t_err_exception         	:		"Error occurred, please try again.",
	js_info_end	:"js_info_end"
},

// File Name:FireWallRpm.htm
ntw_firewall:	{
	t_title                 	:		"Firewall",
	t_en_fw                 	:		"&nbsp;Enable Firewall (the general firewall switch)",
	t_en_ip_flt             	:		"&nbsp;Enable IP Address Filtering",
	t_ip_flt_rule           	:		"Default IP Address Filtering Rules:",
	t_allow0                	:		"Allow",
	t_pcks_pass0            	:		"the packets not specified by any filtering rules to pass through the device",
	t_deny0                 	:		"Deny",
	t_pcks_pass1            	:		"the packets not specified by any filtering rules to pass through the device",
	t_en_domain             	:		"Enable Domain Filtering",
	t_en_mac                	:		"Enable MAC Address Filtering",
	t_mac_flt_rule          	:		"Default MAC Address Filtering Rules:",
	t_allow1                	:		"Allow",
	t_pc_acc0               	:		"these PCs with enabled rules to access the Internet",
	t_deny1                 	:		"Deny",
	t_pc_acc1               	:		"these PCs with enabled rules to access the Internet",
	js_info_end	:"js_info_end"
},

// File Name:FixMapCfgAdvRpm.htm
ntw_fix_map_adv_cfg:	{
	t_title                 	:		"Add or Modify an Address Reservation Entry",
	t_mac_addr              	:		"MAC Address:",
	t_ip_addr               	:		"Reserved IP Address:",
	t_status                	:		"Status:",
	t_disable               	:		"Disabled&nbsp;",
	t_enable                	:		"Enabled&nbsp;",
	js_bad_mac              	:		"Invalid MAC address, please input another one!",	
	js_input_mac            	:		"Please input a correct MAC address!",	
	js_input_ip             	:		"Please input IP address!",	
	js_no_modification      	:		"No modifications, come back?",	
	js_info_end	:"js_info_end"
},

// File Name:FixMapCfgRpm.htm
ntw_fix_map_cfg:	{
	t_title                 	:		"Address Reservation",
	t_mac_addr              	:		"MAC Address",
	t_ip_addr               	:		"Reserved IP Address",
	t_status                	:		"Status",
	t_modify                	:		"Modify",
	t_disable               	:		"Disabled",
	t_enable                	:		"Enabled",
	t_modify1               	:		"Modify",
	t_delete                	:		"Delete",
	t_reboot_msg            	:		"You have modified the system configuration, it will not take effect until the device reboot!",
	js_mksure_delete        	:		"Are you sure to delete all entries?",	
	js_info_end	:"js_info_end"
},

// File Name:GetGMTRpm.htm
ntw_get_gmt:	{
	t_title                 	:		"Getting GMT",
	t_text0                 	:		"Obtaining Network Time from Internet . . .",
	t_text1                 	:		"Please Wait . . .",
	js_info_end	:"js_info_end"
},

// File Name:L2TPCfgRpm.htm
ntw_l2tp_cfg:	{
	t_dyna                  	:		"Dynamic IP",
	t_stat                  	:		"Static IP",
	t_pppoe                 	:		"PPPoE/Russia PPPoE",
	t_802dy                 	:		"802.1X + Dynamic IP",
	t_802st                 	:		"802.1X + Static IP",
	t_bpa                   	:		"BigPond Cable",
	t_l2tp                  	:		"L2TP/Russia L2TP",
	t_pptp                  	:		"PPTP/Russia PPTP",
	t_dualaccess            	:		"Dual Access/Russia PPPoE",
	t_dhpcplus              	:		"DHCP+",
	t_title                 	:		"WAN",
	t_wan_port              	:		"WAN Port:",
	t_wan_con_type          	:		"WAN Connection Type:",
	t_usr_name              	:		"User Name:",
	t_pwd                   	:		"Password:",
	t_disconnected          	:		"Disconnected!",
	t_connected             	:		"Connected!",
	t_Connecting            	:		"Connecting...",
	t_dynamic_ip            	:		"Dynamic IP",
	t_static_ip             	:		"Static IP",
	t_srv_ip_name           	:		"Server IP Address/Name:",
	t_ip_addr               	:		"IP Address:",
	t_sub_mask              	:		"Subnet Mask:",
	t_gateway               	:		"Default Gateway:",
	t_dns                   	:		"DNS:",
	t_internet_ip_addr      	:		"Internet IP Address:",
	t_internet_dns          	:		"Internet DNS:",
	t_mtu_size              	:		"MTU Size (in bytes):",
	t_mtu_def               	:		"(The default is 1460. Do not change it unless necessary.)",
	t_max_idle_time         	:		"Max Idle Time:",
	t_time_def              	:		"minutes (0 means remaining active all the time.)",
	t_wan_con_mode          	:		"WAN Connection Mode:",
	t_con_to_demand         	:		"Connect on Demand",
	t_con_auto              	:		"Connect Automatically",
	t_con_manu              	:		"Connect Manually",
	js_bad_mtu              	:		"Bad MTU, please input another number!\n(576 ~ 1460, the default is 1460)",	
	js_bad_idle_time        	:		"Bad idle time,please input a number!",	
	js_info_end	:"js_info_end"
},

// File Name:LanArpBindingAdvRpm.htm
ntw_lan_arp_binding_adv:	{
	t_title                 	:		"IP & MAC Binding Settings",
	t_bind                  	:		"Bind:",
	t_mac_add               	:		"MAC Address:",
	t_ip_addr               	:		"IP Address:",
	js_bad_mac              	:		"Invalid MAC address, please input again!",	
	js_input_mac            	:		"Please input a correct MAC address!",	
	js_input_ip             	:		"Please input a correct IP address!",	
	js_info_end	:"js_info_end"
},

// File Name:LanArpBindingFindRpm.htm
ntw_lan_arp_binding_find:	{
	t_title                 	:		"Find IP & MAC Binding Entry",
	t_mac_add               	:		"MAC Address:",
	t_ip_addr               	:		"IP Address:",
	t_id                    	:		"ID",
	t_mac_add0              	:		"MAC Address",
	t_ip_addr1              	:		"IP Address",
	t_bind                  	:		"Bind",
	t_link                  	:		"Link",
	t_to_page               	:		"To page",
	t_empty                 	:		"Now the current list is empty.",
	js_mksure_delete        	:		"Are you sure delete all entries?",	
	js_bad_mac              	:		"Invalid MAC address, please input again!",	
	js_cannot_both_none     	:		"The MAC address and IP Address can not be null at the same time!",	
	js_info_end	:"js_info_end"
},

// File Name:LanArpBindingListRpm.htm
ntw_lan_arp_binding_list:	{
	t_title                 	:		"ARP List",
	t_id                    	:		"ID",
	t_mac_addr              	:		"MAC Address",
	t_ip_addr               	:		"IP Address",
	t_status                	:		"Status",
	t_cfg                   	:		"Configure",
	t_bound                 	:		"Bound",
	t_unbound               	:		"Unbound",
	t_load                  	:		"Load",
	t_delete                	:		"Delete",
	t_no_enpty              	:		"The current list is empty.",
	js_info_end	:"js_info_end"
},

// File Name:LanArpBindingRpm.htm
ntw_lan_arp_binding:	{
	t_title                 	:		"Binding Settings",
	t_arp_bind              	:		"ARP Binding:",
	t_disable               	:		"Disable ",
	t_enable                	:		"Enable",
	t_id                    	:		"ID",
	t_mac_addr              	:		"MAC Address",
	t_ip_addr               	:		"IP Address",
	t_bind                  	:		"Bind",
	t_modify                	:		"Modify",
	t_modify1               	:		"Modify",
	t_delete                	:		"Delete",
	t_no_entry              	:		"The list is empty",
	t_page                  	:		"Page",
	js_mksure_delete        	:		"Are you sure delete all entries?",	
	js_info_end	:"js_info_end"
},

// File Name:LanDhcpServerRpm.htm
ntw_lan_dhcp_server:	{
	t_title                 	:		"DHCP Settings",
	t_dhcp_srv              	:		"DHCP Server:",
	t_disable               	:		"Disable ",
	t_enable                	:		"Enable",
	t_start_ip_addr         	:		"Start IP Address:",
	t_end_ip_addr           	:		"End IP Address:",
	t_lease_time            	:		"Address Lease Time:",
	t_defminute             	:		"&nbsp;minutes (1~2880 minutes, the default value is 120)",
	t_default_gateway       	:		"Default Gateway:",
	t_optional              	:		" (optional)",
	t_default_domain        	:		"Default Domain:",
	t_optional0             	:		" (optional)",
	t_primary_dns           	:		"Primary DNS:",
	t_optional1             	:		" (optional)",
	t_secondary_dns         	:		"Secondary DNS:",
	t_optional2             	:		" (optional)",
	t_reboot_msg            	:		"You have modified the system configuration, it will not take effect until the device reboot!",
	js_begin_ip             	:		"Please input Start IP Address!",	
	js_end_ip               	:		"Please input End IP Address!",	
	js_info_end	:"js_info_end"
},

// File Name:LanMacFilterAdvRpm.htm
ntw_lan_mac_filter_adv:	{
	t_title                 	:		"Add or Modify a MAC Address Filtering Entry",
	t_mac_addr              	:		"MAC Address:",
	t_description           	:		"Description:",
	t_status                	:		"Status:",
	t_disable               	:		"Disabled",
	t_enable                	:		"Enabled",
	js_bad_mac              	:		"Invalid MAC address, please input another one!",	
	js_input_mac            	:		"Please input a correct MAC address!",	
	js_info_end	:"js_info_end"
},

// File Name:LanMacFilterRpm.htm
ntw_lan_mac_filter:	{
	t_title                 	:		"MAC Address Filtering",
	t_fw_settings           	:		"Firewall Settings (You can change them on Firewall page)",
	t_en_fw                 	:		"Enable Firewall:",
	t_en_mac_flt            	:		"Enable MAC Address Filtering:",
	t_flt_rul               	:		"Default Filtering Rules:",
	t_mac_add               	:		"MAC Address",
	t_description           	:		"Description",
	t_status                	:		"Status",
	t_modify                	:		"Modify",
	t_enable                	:		"Enabled",
	t_disable               	:		"Disabled",
	t_modify1               	:		"Modify",
	t_delete                	:		"Delete",
	t_enabled               	:		"Enabled",
	t_disabled              	:		"Disabled",
	t_allow                 	:		"Allow ",
	t_pc_acc                	:		" these PCs with the enabled rules to access the Internet.",
	t_deny                  	:		"Deny ",
	t_pc_acce               	:		" these PCs with the enabled rules to access the Internet.",
	js_mksure_delete        	:		"Are you sure to delete all entries?",	
	js_info_end	:"js_info_end"
},

// File Name:MacCloneCfgRpm.htm
ntw_mac_clone_cfg:	{
	t_title                 	:		"MAC Clone",
	t_mac_addr              	:		"WAN MAC Address:",
	t_pc_mac_addr           	:		"Your PC's MAC Address:",
	js_reboot_prompt        	:		"The function won't take effect until the device reboot.Are you sure to reboot the device now?",	
	js_bad_mac              	:		"Invalid MAC address, please input another one!",	
	js_info_end	:"js_info_end"
},

// File Name:ManageControlRpm.htm
ntw_manage_control:	{
	t_title                 	:		"Remote Management",
	t_manage_port           	:		"Web Management Port:",
	t_manage_ip_addr        	:		"Remote Management IP Address:",
	t_reboot_msg            	:		"You have modified the system configuration, it will not take effect until the device reboot!",
	js_bad_manage_port      	:		"The port number is invalid, please input another one(80,1024-65534)!",	
	js_info_end	:"js_info_end"
},

// File Name:MiscShowRpm.htm
ntw_misc_show:	{
	t_title                 	:		"Blocked DoS Host List",
	t_host_ip               	:		"Host IP Address",
	t_host_mac              	:		"Host MAC Address",
	t_no_host               	:		"No thwarted DoS Host.",
	js_info_end	:"js_info_end"
},

// File Name:NetworkLanCfgRpm.htm
ntw_network_lan_cfg:	{
	t_title                 	:		"LAN",
	t_mac_addr              	:		"MAC Address:",
	t_ip_addr               	:		"IP Address:",
	t_mask                  	:		"Subnet Mask:",
	js_input_ip             	:		"Please input IP address!",	
	js_reboot_prompt        	:		"Modification of IP address or Subnet Mask will result in the rebooting of the device,OK?",	
	js_info_end	:"js_info_end"
},

// File Name:PeanutHullDdnsRpm.htm
ntw_peanuthull_ddns:	{
	t_title                 	:		"DDNS",
	t_srv_provider          	:		"Service Provider:",
	t_register              	:		"Go to register...",
	t_wan_port              	:		"WAN Port:",
	t_usr_name              	:		"User Name:",
	t_pwd                   	:		"Password:",
	t_en_ddns               	:		"&nbsp;Enable DDNS",
	t_cnn_status            	:		"Connection Status:",
	t_type                  	:		"Service Type:",
	t_domain_name           	:		"Domain Name:",
	t_null                  	:		"---",
	t_not_launch            	:		"DDNS not launching!",
	t_connecting            	:		"Connecting...",
	t_succeeded             	:		"Succeeded!",
	t_pwd_error             	:		"User or Password error!",
	t_domain_error          	:		"Domain Name error",
	t_profession_service    	:		"Profession Service",
	t_standard_service      	:		"Standard Service",
	js_info_end	:"js_info_end"
},

// File Name:PPPoECfgAdvRpm.htm
ntw_pppoe_cfg_adv:	{
	t_title                 	:		"PPPoE Advanced Settings",
	t_mtu_size              	:		"MTU Size (in bytes):",
	t_mtu_size_range        	:		"&nbsp;(The default is 1480, do not change unless necessary.)",
	t_ser_name              	:		"Service Name:",
	t_ac_name               	:		"AC Name:",
	t_ip_addr_desc          	:		"&nbsp;Use IP address specified by ISP",
	t_isp_ip                	:		"ISP Specified IP Address:",
	t_detect_interval       	:		"Detect Online Interval:",
	t_sec                   	:		"&nbsp;Seconds	(0 ~ 120 seconds, the default is 0, 0 means not detecting.)",
	t_use_dns_ser           	:		"&nbsp;Use the following DNS Servers",
	t_pri_dns               	:		"Primary DNS:",
	t_sec_dns               	:		"Secondary DNS:",
	t_op                    	:		"&nbsp;(Optional)",
	js_bad_mtu              	:		"The MTU is invalid, please input another one!(576 ~ 1492, the default is 1480)!",	
	js_detect_interval_error	:		"The 'Detect Online Interval' must be between 0~120!",	
	js_reboot_prompt        	:		"Save the configuration will result in reconnecting to the Internet, OK?",	
	js_info_end	:"js_info_end"
},

// File Name:PPPoECfgRpm.htm
ntw_pppoe_cfg:	{
	t_dyna                  	:		"Dynamic IP",
	t_stat                  	:		"Static IP",
	t_pppoe                 	:		"PPPoE/Russia PPPoE",
	t_802dy                 	:		"802.1X + Dynamic IP",
	t_802st                 	:		"802.1X + Static IP",
	t_bpa                   	:		"BigPond Cable",
	t_l2tp                  	:		"L2TP/Russia L2TP",
	t_pptp                  	:		"PPTP/Russia PPTP",
	t_dualaccess            	:		"Dual Access/Russia PPPoE",
	t_dhpcplus              	:		"DHCP+",
	t_title                 	:		"WAN",
	t_wan_port              	:		"WAN Port:",
	t_wan_con_type          	:		"WAN Connection Type:",
	t_usr_name              	:		"User Name:",
	t_pwd                   	:		"Password:",
	t_wan_con_mod           	:		"WAN Connection Mode:",
	t_conn_on_demand        	:		"Connect on Demand",
	t_max_idle_time         	:		"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Max Idle Time: &nbsp;",
	t_mins                  	:		" minutes (0 means remaining active all the time.)",
	t_con_auto              	:		"Connect Automatically",
	t_time_base             	:		"Time-based Connecting",
	t_period_time           	:		"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Period of Time:from&nbsp;",
	t_hm                    	:		"(HH:MM) to",
	t_conn_manu             	:		"Connect Manually",
	t_max_idle_time1        	:		"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Max Idle Time: &nbsp;",
	t_mins1                 	:		" minutes (0 means remaining active all the time.)",
	t_disconnected          	:		"Disconnected",
	t_connected             	:		"Connected",
	t_connecting            	:		"Connecting...",
	js_bad_waittime         	:		"Wrong time format, please input another number (0-99)!",	
	js_bad_hour             	:		"Wrong time format, please input another number (0-23)!",	
	js_input_time           	:		"Please input a time!",	
	js_bad_minute           	:		"Wrong time format, please input another number (0-59)!",	
	js_info_end	:"js_info_end"
},

// File Name:PPTPCfgRpm.htm
ntw_pptp_cfg:	{
	t_dyna                  	:		"Dynamic IP",
	t_stat                  	:		"Static IP",
	t_pppoe                 	:		"PPPoE/Russia PPPoE",
	t_802dy                 	:		"802.1X + Dynamic IP",
	t_802st                 	:		"802.1X + Static IP",
	t_bpa                   	:		"BigPond Cable",
	t_l2tp                  	:		"L2TP/Russia L2TP",
	t_pptp                  	:		"PPTP/Russia PPTP",
	t_dualaccess            	:		"Dual Access/Russia PPPoE",
	t_dhpcplus              	:		"DHCP+",
	t_title                 	:		"WAN",
	t_wan_port              	:		"WAN Port:",
	t_wan_con_type          	:		"WAN Connection Type:",
	t_usr_name              	:		"User Name:",
	t_pwd                   	:		"Password:",
	t_disconnected          	:		"Disconnected!",
	t_connected             	:		"Connected!",
	t_Connecting            	:		"Connecting...",
	t_dyn_ip                	:		"Dynamic IP",
	t_stat_ip               	:		"Static IP",
	t_srv_ip_addr_name      	:		"Server IP Address/Name:",
	t_ip_addr               	:		"IP Address:",
	t_sub_mask              	:		"Subnet Mask:",
	t_gateway               	:		"Default Gateway:",
	t_dns                   	:		"DNS:",
	t_internet_ip_addr      	:		"Internet IP Address:",
	t_internet_dns          	:		"Internet DNS:",
	t_mtu_size              	:		"MTU Size (in bytes):",
	t_text1                 	:		"&nbsp;(The default is 1420. Do not change it unless necessary.)",
	t_max_idle_time         	:		"Max Idle Time:",
	t_text2                 	:		"&nbsp;minutes (0 means remaining active all the time.)",
	t_wan_con_mode          	:		"WAN Connection Mode:",
	t_connectondemand       	:		"Connect on Demand",
	t_connectauto           	:		"Connect Automatically",
	t_connectmaually        	:		"Connect Manually",
	js_bad_mtu              	:		"Bad MTU, please input another number!\n(576 ~ 1460, the default is 1420)",	
	js_bad_idle_time        	:		"Bad idle time,please input a number!",	
	js_info_end	:"js_info_end"
},

// File Name:restart.htm
restart:	{
	t_title                 	:		"Restart",
	t_config_upload         	:		"Config Upload Successfully!",
	t_change_LAN_IP         	:		"Change LAN IP address Successfully!",
	t_MAC_clone             	:		"MAC Clone Successfully!",
	t_software_upgrade      	:		"Software Upgrade Successfully!",
	t_router_reboot         	:		"Device Reboot Successfully!",
	t_factory_default       	:		"Reset Factory Config Successfully!",
	t_pppoe                 	:		"PPPoE Setting Successfully!",
	t_config_upload_ex      	:		"Config Upload Successfully,but there are some unknown commands:",
	t_setting_succeed       	:		"Setting Successfully.",
	t_notice                	:		"Please wait a moment, if the browser does not refresh automatically, click Refresh in the top of your browser.",
	js_info_end	:"js_info_end"
},

// File Name:RestoreDefaultCfgRpm.htm
ntw_restore_default_cfg:	{
	t_title                 	:		"Factory Defaults",
	t_notice                	:		"Click the following button to reset all configuration settings to their default values.",
	js_mksure_restore       	:		"Any settings you have saved will be lost if you restore Factory Defaults, \nare you sure to continue?",	
	js_info_end	:"js_info_end"
},

// File Name:SoftwareUpgradeRpm.htm
ntw_software_upgrade:	{
	t_title                 	:		"Firmware Upgrade",
	t_file                  	:		"File:",
	t_softversion           	:		"Firmware Version:",
	t_hardversion           	:		"Hardware Version:",
	js_input_file           	:		"Please choose a file to upgrade!",	
	js_choose_file          	:		"Please choose a correct file to upgrade!",	
	js_bad_file             	:		"The filename should not be longer than 64!",	
	js_mksure_upgrade       	:		"Are you sure to upgrade the firmware?",	
	js_err_file_len         	:		"The file size oversteps the allowable value!",	
	js_info_end	:"js_info_end"
},

// File Name:SpecialAppAdvRpm.htm
ntw_special_app_adv:	{
	t_title                 	:		"Add or Modify a Port Triggering Entry",
	t_trigger_port          	:		"Trigger Port:",
	t_trigger_protocol      	:		"Trigger Protocol:",
	t_all                   	:		"ALL",
	t_incomming_port        	:		"Incoming Ports:",
	t_incomming_protocol    	:		"Incoming Protocol:",
	t_all2                  	:		"ALL",
	t_status                	:		"Status:",
	t_disable               	:		"Disabled",
	t_enable                	:		"Enabled",
	t_common_app            	:		"Common Applications:",
	t_select_one            	:		"--Select One--",
	js_bad_port_range       	:		"Port number must be in range (1-65534), please input another number!",	
	js_input_error          	:		"The input value contain illegal character, please input another one!",	
	js_port_illegal         	:		"Illegal port, please input another one!",	
	js_input_trigger_port   	:		"Please input the Trigger Port number!",	
	js_input_incoming_port  	:		"Please input the Incoming Ports number!",	
	js_info_end	:"js_info_end"
},

// File Name:SpecialAppRpm.htm
ntw_special_app:	{
	t_all                   	:		"ALL",
	t_title                 	:		"Port Triggering",
	t_id                    	:		"ID",
	t_trig_port             	:		"Trigger Port",
	t_trig_protocol         	:		"Trigger Protocol",
	t_incom_port            	:		"Incoming Ports",
	t_incom_protocol        	:		"Incoming Protocol",
	t_status                	:		"Status",
	t_modify                	:		"Modify",
	t_disabled              	:		"Disabled",
	t_enabled               	:		"Enabled",
	t_modify1               	:		"Modify",
	t_Delete                	:		"Delete",
	js_no_entry             	:		"No entry existed in the table!",	
	js_mksure_delete        	:		"Are you sure to delete all entries?",	
	js_info_end	:"js_info_end"
},

// File Name:StaticRouteTableAdvRpm.htm
ntw_static_route_table_adv:	{
	t_title                 	:		"Add or Modify a Static Route Entry",
	t_dest_ipaddr           	:		"Destination IP Address:",
	t_submask               	:		"Subnet Mask:",
	t_gateway               	:		"Default Gateway:",
	t_status                	:		"Status:",
	t_disabled              	:		"Disabled&nbsp;",
	t_enabled               	:		"Enabled&nbsp;",
	js_input_ip             	:		"Please input IP address!",	
	js_input_mask           	:		"Please input the subnet mask address!",	
	js_input_gateway        	:		"Please input Gateway address!",	
	js_info_end	:"js_info_end"
},

// File Name:StaticRouteTableRpm.htm
ntw_static_route_table:	{
	t_title                 	:		"Static Routing List",
	t_dest_ipaddr           	:		"Destination IP Address",
	t_submask               	:		"Subnet Mask",
	t_gateway               	:		"Default Gateway",
	t_status                	:		"Status",
	t_modify                	:		"Modify",
	t_disable               	:		"Disabled",
	t_enable                	:		"Enabled",
	t_modify1               	:		"Modify",
	t_delete                	:		"Delete",
	js_mksure_delete        	:		"Are you sure to delete all entries?",	
	js_info_end	:"js_info_end"
},

// File Name:SysRebootRpm.htm
ntw_sys_reboot:	{
	t_title                 	:		"Reboot",
	t_notice                	:		"Click this button to reboot the device.",
	js_mksure_reboot        	:		"Are you sure to reboot the Device?",	
	js_info_end	:"js_info_end"
},

// File Name:SystemLogRpm.htm
ntw_sys_log:	{
	t_title                 	:		"System Log",
	t_index                 	:		"Index",
	t_log                   	:		"Log Content",
	js_mksure_delete        	:		"Are you sure to clear all the logs?",	
	js_info_end	:"js_info_end"
},

// File Name:SystemStatisticRpm.htm
ntw_system_statistic:	{
	t_title                 	:		"Statistics",
	t_current_status        	:		"Current Statistics Status:",
	t_pck_sta_int           	:		"Packets Statistics Interval(5~60):",
	t_sec                   	:		"&nbsp;Seconds",
	t_auto_ref              	:		"&nbsp;Auto-refresh",
	t_srt_rul               	:		"Sorted Rules:",
	t_by_ip                 	:		"Sorted by IP Address",
	t_by_total_packet       	:		"Sorted by Total Packets",
	t_by_total_byte         	:		"Sorted by Total Bytes",
	t_by_cur_packet         	:		"Sorted by Current Packets",
	t_by_cur_byte           	:		"Sorted by Current Bytes",
	t_total                 	:		"Total",
	t_current               	:		"Current",
	t_modify                	:		"Modify",
	t_ip_addr               	:		"IP Address/",
	t_mac_addr              	:		"MAC Address",
	t_packet0               	:		"Packets",
	t_byte0                 	:		"Bytes",
	t_packet1               	:		"Packets",
	t_byte1                 	:		"Bytes",
	t_icmp_tx               	:		"ICMP Tx",
	t_udp_tx                	:		"UDP Tx",
	t_syn_tx                	:		"SYN Tx",
	t_reset                 	:		"Reset",
	t_delete                	:		"Delete",
	t_no_entry              	:		"The current list is empty.",
	t_page                  	:		"Page",
	t_enabled               	:		"Enabled",
	t_disabled              	:		"Disabled",
	js_mksure_reset         	:		"Are you sure to reset all statistics?",	
	js_mksure_delete        	:		"Are you sure to delete all entries?",	
	js_info_end	:"js_info_end"
},

// File Name:UpdateTemp.htm
ntw_update_temp:	{
	t_title0                	:		"Configuration Import",
	t_title1                	:		"Firmware Upgrade",
	t_notice0               	:		"Processing...",
	t_notice1               	:		"Please wait until system reboots...",
	js_info_end	:"js_info_end"
},

// File Name:UpnpCfgRpm.htm
ntw_upnp_cfg:	{
	t_titlt                 	:		"UPnP",
	t_status                	:		"Status",
	t_disabled1             	:		"Disabled",
	t_enabled1              	:		"Enabled",
	t_curlist               	:		"Current UPnP Settings List",
	t_id                    	:		"ID",
	t_app                   	:		"App Description",
	t_ex_port               	:		"External Port",
	t_protocol              	:		"Protocol",
	t_inter_port            	:		"Internal Port",
	t_ip                    	:		"IP Address",
	t_status1               	:		"Status",
	t_disabled              	:		"Disabled",
	t_enabled               	:		"Enabled",
	js_info_end	:"js_info_end"
},

// File Name:VirtualServerAdvRpm.htm
ntw_virtual_server_adv:	{
	t_title                 	:		"Add or Modify a Virtual Server Entry",
	t_srv_port              	:		"Service Port:",
	t_format                	:		"(XX-XX or XX)",
	t_ip_addr               	:		"IP Address:",
	t_protocol              	:		"Protocol:",
	t_all                   	:		"ALL",
	t_status                	:		"Status:",
	t_disable               	:		"Disabled",
	t_enable                	:		"Enabled",
	t_common                	:		"Common Service Port:",
	t_select_one            	:		"--Select One--",
	js_input_illegal        	:		"The input value contain illegal character, please input another one!",	
	js_port_illegal         	:		"Illegal port input, please input another one! For e.g.: 21-26 or 23.",	
	js_input_ip             	:		"Please input IP address!",	
	js_input_port           	:		"Please input port address! For e.g.: 21-26 or 23",	
	js_info_end	:"js_info_end"
},

// File Name:VirtualServerRpm.htm
ntw_virtual_server:	{
	t_all                   	:		"ALL",
	t_title                 	:		"Virtual Servers",
	t_id                    	:		"ID",
	t_srv_port              	:		"Service Ports",
	t_ip_addr               	:		"IP Address",
	t_protocol              	:		"Protocol",
	t_status                	:		"Status",
	t_modify                	:		"Modify",
	t_enable                	:		"Enabled",
	t_disable               	:		"Disabled",
	t_modify1               	:		"Modify",
	t_delete                	:		"Delete",
	js_no_entry             	:		"No entry exists in the table!",	
	js_mksure_delete        	:		"Are you sure to delete all entries?",	
	js_info_end	:"js_info_end"
},

// File Name:WanDynamicIpCfgRpm.htm
ntw_wan_dynamic_ip_cfg:	{
	t_dyna                  	:		"Dynamic IP",
	t_stat                  	:		"Static IP",
	t_pppoe                 	:		"PPPoE/Russia PPPoE",
	t_802dy                 	:		"802.1X + Dynamic IP",
	t_802st                 	:		"802.1X + Static IP",
	t_bpa                   	:		"BigPond Cable",
	t_l2tp                  	:		"L2TP/Russia L2TP",
	t_pptp                  	:		"PPTP/Russia PPTP",
	t_dualaccess            	:		"Dual Access/Russia PPPoE",
	t_dhpcplus              	:		"DHCP+",
	t_title                 	:		"WAN",
	t_wan_port              	:		"WAN Port:",
	t_wan_con_type          	:		"WAN Connection Type:",
	t_in_net_ran            	:		"Interior network:",
	t_host_name             	:		"Host Name:",
	t_ip_addr               	:		"IP Address:",
	t_sub_mask              	:		"Subnet Mask:",
	t_gateway               	:		"Default Gateway:",
	t_info                  	:		"Obtaining network parameters...",
	t_disconnected          	:		"Wan is disconnected!",
	t_mtu_size              	:		"MTU Size (in bytes):",
	t_mtu_range             	:		"&nbsp;(The default is 1500. Do not change it unless necessary.)",
	t_use_dns_srv           	:		"&nbsp;Use These DNS Servers",
	t_pri_dns               	:		"Primary DNS:",
	t_sec_dns               	:		"Secondary DNS:",
	t_opt                   	:		"&nbsp;(Optional)",
	t_get_ip_dncp           	:		"&nbsp;Get IP with Unicast DHCP (It is usually not required.)",
	js_bad_mtu              	:		"Bad MTU, please input another number!(576 ~ 1500, the default is 1500)",	
	js_bad_interior_network 	:		"The Interior network is invalid, please input again!",	
	js_info_end	:"js_info_end"
},

// File Name:WanDynamicIpCfgRpm_8021X.htm
ntw_wan_dynamic_ip_cfg_8021x:	{
	t_dyna                  	:		"Dynamic IP",
	t_stat                  	:		"Static IP",
	t_pppoe                 	:		"PPPoE/Russia PPPoE",
	t_802dy                 	:		"802.1X + Dynamic IP",
	t_802st                 	:		"802.1X + Static IP",
	t_bpa                   	:		"BigPond Cable",
	t_l2tp                  	:		"L2TP/Russia L2TP",
	t_pptp                  	:		"PPTP/Russia PPTP",
	t_dualaccess            	:		"Dual Access/Russia PPPoE",
	t_dhpcplus              	:		"DHCP+",
	t_title                 	:		"WAN",
	t_wan_con_type          	:		"WAN Connection Type:",
	t_usr_name              	:		"User Name:",
	t_pwd                   	:		"Password:",
	t_fail                  	:		"Login failed!",
	t_not                   	:		"Not log in",
	t_success               	:		"Login successfully",
	t_wait                  	:		"Logging in ...",
	t_ip_addr               	:		"IP Address:",
	t_sub_mask              	:		"Subnet Mask:",
	t_gateway               	:		"Default Gateway:",
	t_mtu_size              	:		"MTU Size (in bytes):",
	t_remaind_mtu           	:		"&nbsp;(The default is 1500. Do not change it unless necessary.)",
	t_remaind_dns           	:		"&nbsp;Use These DNS Servers",
	t_pri_dns               	:		"Primary DNS:",
	t_sec_dns               	:		"Secondary DNS:",
	t_optional              	:		"&nbsp;(Optional)",
	t_get_ip_dncp           	:		"&nbsp;Get IP with Unicast DHCP (It is usually not required.)",
	js_bad_mtu              	:		"Bad MTU, please input another number!(576 ~ 1500, the default is 1500)",	
	js_info_end	:"js_info_end"
},

// File Name:WanIpFilterAdvRpm.htm
ntw_wan_ip_filter_adv:	{
	t_title                 	:		"Add or Modify an IP Address Filtering Entry",
	t_effect_time           	:		"Effective time:",
	t_lan_ip_addr           	:		"LAN IP Address:",
	t_lan_port              	:		"LAN Port:",
	t_wan_ip_addr           	:		"WAN IP Address:",
	t_wan_port              	:		"WAN Port:",
	t_protocol              	:		"Protocol:",
	t_all                   	:		"ALL",
	t_action                	:		"Action:",
	t_deny                  	:		"Deny",
	t_allow                 	:		"Allow",
	t_status                	:		"Status:",
	t_disabled              	:		"Disabled",
	t_enabled               	:		"Enabled",
	js_bad_start_time       	:		"Bad start time (only 4 numbers), please input another number!",	
	js_bad_end_time         	:		"Bad end time (only 4 numbers), please input another number!",	
	js_bad_lan_ip1          	:		"Bad start LAN IP Address, please input another IP Address!",	
	js_bad_lan_ip2          	:		"Bad end LAN IP Address, please input another IP Address!",	
	js_bad_lan_port1        	:		"Bad start LAN port number!",	
	js_bad_lan_port2        	:		"Bad end LAN port number!",	
	js_bad_wan_ip1          	:		"Bad start WAN IP Address, please input another IP Address!",	
	js_bad_wan_ip2          	:		"Bad end WAN IP Address, please input another IP Address!",	
	js_bad_wan_port1        	:		"Bad start WAN port number!",	
	js_bad_wan_port2        	:		"Bad end WAN port number!",	
	js_info_end	:"js_info_end"
},

// File Name:WanIpFilterRpm.htm
ntw_wan_ip_filter:	{
	t_all                   	:		"ALL",
	t_title                 	:		"IP Address Filtering",
	t_fw_set                	:		"Firewall Settings (You can change them on Firewall page)",
	t_en_fw                 	:		"Enable Firewall:",
	t_en_ip_filter          	:		"Enable IP Address Filtering:",
	t_filter_rule           	:		"Default Filtering Rules:",
	t_id                    	:		"ID",
	t_eff_time              	:		"Effective time",
	t_lan_ip                	:		"LAN IP Address",
	t_lan_port              	:		"LAN Port",
	t_wan_ip                	:		"WAN IP Address",
	t_wan_port              	:		"WAN Port",
	t_proto                 	:		"Protocol",
	t_action                	:		"Action",
	t_status                	:		"Status",
	t_modify                	:		"Modify",
	t_allow                 	:		"Allow",
	t_deny                  	:		"Deny",
	t_enable                	:		"Enabled",
	t_disable               	:		"Disabled",
	t_modify1               	:		"Modify",
	t_delete                	:		"Delete",
	t_toid                  	:		"to ID",
	t_enabled               	:		"Enabled",
	t_disabled              	:		"Disabled",
	t_pcks_pass_router      	:		"&nbsp;the packets not specified by any filtering rules to pass through the device",
	t_pass_router           	:		"the packets not specified by any filtering rules to pass through the device.",
	js_mksure_delete        	:		"Are you sure to delete all entries?",	
	js_no_entry             	:		"There's no entry to move.",	
	js_bad_id               	:		"The id index shouldn't be 0, please change another one",	
	js_input_dest_index     	:		"please input the destination index!",	
	js_input_src_index      	:		"please input the source index!",	
	js_bad_id_index         	:		"The ID index is invalid, please input another one!",	
	js_info_end	:"js_info_end"
},

// File Name:WanStaticIpCfgRpm.htm
ntw_wan_static_ip_cfg:	{
	t_dyna                  	:		"Dynamic IP",
	t_stat                  	:		"Static IP",
	t_pppoe                 	:		"PPPoE/Russia PPPoE",
	t_802dy                 	:		"802.1X + Dynamic IP",
	t_802st                 	:		"802.1X + Static IP",
	t_bpa                   	:		"BigPond Cable",
	t_l2tp                  	:		"L2TP/Russia L2TP",
	t_pptp                  	:		"PPTP/Russia PPTP",
	t_dualaccess            	:		"Dual Access/Russia PPPoE",
	t_dhpcplus              	:		"DHCP+",
	t_title                 	:		"WAN",
	t_wan_port              	:		"WAN Port:",
	t_wan_conn_tp           	:		"WAN Connection Type:",
	t_in_net_ran            	:		"Interior network:",
	t_ip_addr               	:		"IP Address:",
	t_sub_mask              	:		"Subnet Mask:",
	t_gateway               	:		"Default Gateway:",
	t_option                	:		"&nbsp;(Optional)",
	t_mtu_size              	:		"MTU Size (in bytes):",
	t_desc                  	:		"&nbsp;(The default is 1500. Do not change it unless necessary.)",
	t_pri_dns               	:		"Primary DNS:",
	t_option1               	:		"&nbsp;(Optional)",
	t_sec_dns               	:		"Secondary DNS:",
	t_opt2                  	:		"&nbsp;(Optional)",
	js_bad_mtu              	:		"Bad MTU, please input another number!(576 ~ 1500, the default is 1500)",	
	js_bad_interior_network 	:		"The Interior network is invalid, please input again!",	
	js_info_end	:"js_info_end"
},

// File Name:WanStaticIpCfgRpm_8021X.htm
ntw_wan_statis_ip_cfg_8021x:	{
	t_dyna                  	:		"Dynamic IP",
	t_stat                  	:		"Static IP",
	t_pppoe                 	:		"PPPoE/Russia PPPoE",
	t_802dy                 	:		"802.1X + Dynamic IP",
	t_802st                 	:		"802.1X + Static IP",
	t_bpa                   	:		"BigPond Cable",
	t_l2tp                  	:		"L2TP/Russia L2TP",
	t_pptp                  	:		"PPTP/Russia PPTP",
	t_dualaccess            	:		"Dual Access/Russia PPPoE",
	t_dhpcplus              	:		"DHCP+",
	t_title                 	:		"WAN",
	t_wan_coon_type         	:		"WAN Connection Type:",
	t_usr_name              	:		"User Name:",
	t_pwd                   	:		"Password:",
	t_fail                  	:		"Login failed!",
	t_not                   	:		"Not log in",
	t_success               	:		"Login successfully",
	t_wait                  	:		"Logging in ...",
	t_ip_addr               	:		"IP Address:",
	t_sub_mask              	:		"Subnet Mask:",
	t_gateway               	:		"Default Gateway:",
	t_optional              	:		"&nbsp;(Optional)",
	t_mud_size              	:		"MTU Size (in bytes):",
	t_remaind_mtu           	:		"&nbsp;(The default is 1500. Do not change it unless necessary.)",
	t_pri_dns               	:		"Primary DNS:",
	t_optional1             	:		"&nbsp;(Optional)",
	t_sec_dns               	:		"Secondary DNS:",
	t_optional2             	:		"&nbsp;(Optional)",
	js_bad_mtu              	:		"Bad MTU, please input another number!(576 ~ 1500, the default is 1500)",	
	js_info_end	:"js_info_end"
},

// File Name:WlanMacFilterAdvRpm.htm
wlan_mac_fil_adv:	{
	t_title                 	:		"Add or Modify Wireless MAC Address Filtering entry",
	t_mac_addr              	:		"MAC Address:",
	t_description           	:		"Description:",
	t_privilege             	:		"Privilege:",
	t_allow                 	:		"allow",
	t_deny                  	:		"deny",
	t_64bit						:		"64 bit",
	t_128bit					:		"128 bit",
	t_152bit					:		"152 bit",
	t_wep_key					:		"WEP Key:",	
	t_status                	:		"Status:",
	t_enabled               	:		"Enabled",
	t_disabled              	:		"Disabled",
	js_bad_mac              	:		"Invalid MAC address, please input another one!",
	js_pl_cor_mac				:		"Please input a correct MAC address!",
	js_pl_cor_wep				:		"Please input a correct WEP Key!",
	js_info_end	:"js_info_end"
},

// File Name:WlanMacFilterRpm.htm
ntw_wlan_mac_filter:	{
	t_title						:		"Wireless MAC Filtering",
	t_currentSSID				:		"Current SSID:",
	t_macAddrFlt               	:		"Wireless MAC Filtering:",
	t_disabled              	:		"Disabled",
	t_enabled               	:		"Enabled",
	t_flt_rule              	:		"Filtering Rules",
	t_allow                 	:		"Allow",
	t_allow_note            	:		"the stations not specified by any enabled entries in the list to access.",
	t_deny                  	:		"Deny",
	t_deny_note             	:		"the stations not specified by any enabled entries in the list to access.",
	t_id						:		"ID",
	t_mac_addr              	:		"MAC Address",
	t_status                	:		"Status",
	t_priv                  	:		"Privilege",
	t_wep_key					:		"WEP Key",
	t_dsp                   	:		"Description",
	t_modify                	:		"Modify",
	t_wl_mac_en					:		"Enabled",
	t_wl_mac_dis				:		"Disabled",
	t_but_modi					:		"Modify",
	t_delete					:		"Delete",
	t_allow1                	:		"allow",
	t_deny1                 	:		"deny",
	t_64bit						:		"64 bit",
	t_128bit					:		"128 bit",
	t_152bit					:		"152 bit",
	js_to_del_rul        		:		"Are you sure to delete all entries?",	
	js_to_change_rule   		:		"Do you want to change current Filtering Rules?",	
	js_info_end	:"js_info_end"
},

// File Name:WlanStationRpm.htm
ntw_wlan_station:	{
	t_auth                  	:		"STA-AUTH",
	t_assoc                 	:		"STA-ASSOC",
	t_up                    	:		"AP-UP",
	t_down                  	:		"AP-DOWN",
	t_disconed              	:		"Disconnected",
	t_title                 	:		"Wireless Statistics",
	t_cur_number            	:		"Current Connected Wireless Stations numbers:",
	t_id                    	:		"ID",
	t_mac_addr              	:		"MAC Address",
	t_cur_status            	:		"Current Status",
	t_rev_pkt               	:		"Received Packets",
	t_sent_pkt              	:		"Sent Packets",
	js_info_end	:"js_info_end"
},

// File Name:WzdEndRpm.htm
ntw_wzd_end:	{
	t_title                 	:		"Quick Setup - Finish",
	t_msg                   	:		"Congratulations! The device is now connecting you to the Internet. For detail settings, please contact other menus if necessary.",
	js_info_end	:"js_info_end"
},

// File Name:WzdWanAutoTypeRpm.htm
ntw_wzd_wan_auto:	{
	t_title                 	:		"Quick Setup - WAN Connection Type",
	t_cable_unplgged			:		"The cable is unplugged.",
	t_pl_plug					:		"Before continuing, please make sure the cable of the WAN port is well connected to your device.",
	js_info_end	:"js_info_end"
},

// File Name:WzdPPPoERpm.htm
ntw_wzd_pppoe:	{
	t_title                 	:		"Quick Setup - PPPoE",
	t_name                  	:		"User Name:",
	t_pwd                   	:		"Password: ",
	t_pwd_confirm				:		"Confirm Password:",
	js_input_name           	:		"Please input an Account Name!",	
	js_input_pwd            	:		"Please input a Password!",	
	js_confirm_different		:		"The Password is different from the Confirm Password!",
	js_info_end	:"js_info_end"
},

// File Name:WzdStartRpm.htm
ntw_wzd_start:	{
	t_title                 	:		"Quick Setup",
	t_guide1                	:		"The quick setup will tell you how to configure the basic network parameters.",
	t_guide2_1              	:		"To continue, please click the ",
	t_guide2_2              	:		"Next",
	t_guide2_3              	:		"button.",
	t_guide3_1              	:		"To exit, please click the ",
	t_guide3_2              	:		"Exit",
	t_guide3_3              	:		"&nbsp;button.",
	js_info_end	:"js_info_end"
},

// File Name:WzdStaticIpRpm.htm
ntw_wzd_static_ip:	{
	t_title                 	:		"Quick Setup - Static IP",
	t_ip                    	:		"IP Address:",
	t_submask               	:		"Subnet Mask:",
	t_default_gateway       	:		"Default Gateway:",
	t_option                	:		"(Optional)",
	t_dns1                  	:		"Primary DNS:",
	t_option1               	:		"(Optional)",
	t_dns2                  	:		"Secondary DNS:",
	t_option2               	:		"(Optional)",
	js_info_end	:"js_info_end"
},

// File Name:WzdWanTypeRpm.htm
ntw_wzd_wan_type:	{
	t_title                 	:		"Quick Setup - WAN Connection Type",
	t_item                  	:		"The Quick Setup is preparing to set up your connection type of WAN port.",
	t_prompt					:		"The Router will try to detect the Internet connection type your ISP provides if you select the ",
	t_option					:		" option.",
	t_man_specify				:		"Otherwise, you need to specify the connection type manually.",
	t_auto_detect_opt			:		"Auto-Detect",
	t_auto						:		"Let the Router automatically detect the connection type your ISP provides.",
	t_pppoe_opt					:		"PPPoE",
	t_pppoe                 	:		"For this connection, your will need your account name and password from your ISP.",
	t_dhcp_opt					:		"Dynamic IP",
	t_dhcp	                 	:		"Your ISP uses a DHCP service to assign your Router an IP address when connecting to the Internet.",
	t_static_ip_opt				:		"Static IP",
	t_static_ip					:		"This type of connection uses a permanent, fixed (static) IP address that your ISP assigned.",
	js_info_end	:"js_info_end"
},

// File Name:DualAccessCfgAdvRpm.htm
ntw_dual_access_cfg_adv:	{
	t_title                 	:		"Dual Access Advanced Settings",
	t_mtu_size              	:		"MTU Size (in bytes):",
	t_mtu_size_range        	:		"&nbsp;(The default is 1480, do not change unless necessary.)",
	t_ser_name              	:		"Service Name:",
	t_ac_name               	:		"AC Name:",
	t_ip_addr_desc          	:		"&nbsp;Use IP address specified by ISP",
	t_isp_ip                	:		"ISP Specified IP Address:",
	t_detect_interval       	:		"Detect Online Interval:",
	t_sec                   	:		"&nbsp;Seconds	(0 ~ 120 seconds, the default is 0, 0 means not detecting.)",
	t_use_dns_ser           	:		"&nbsp;Use the following DNS Servers",
	t_pri_dns               	:		"Primary DNS:",
	t_sec_dns               	:		"Secondary DNS:",
	t_op                    	:		"&nbsp;(Optional)",
	js_bad_mtu              	:		"The MTU is invalid, please input another one!(576 ~ 1492, the default is 1480)!",	
	js_detect_interval_error	:		"The 'Detect Online Interval' must be between 0~120!",	
	js_reboot_prompt        	:		"Save the configuration will result in reconnecting to the Internet, OK?",	
	js_info_end	:"js_info_end"
},

// File Name:DualAccessCfgRpm.htm
ntw_dual_access_cfg:	{
	t_dyna                  	:		"Dynamic IP",
	t_stat                  	:		"Static IP",
	t_pppoe                 	:		"PPPoE/Russia PPPoE",
	t_802dy                 	:		"802.1X + Dynamic IP",
	t_802st                 	:		"802.1X + Static IP",
	t_bpa                   	:		"BigPond Cable",
	t_l2tp                  	:		"L2TP/Russia L2TP",
	t_pptp                  	:		"PPTP/Russia PPTP",
	t_dualaccess            	:		"Dual Access/Russia PPPoE",
	t_dhpcplus              	:		"DHCP+",
	t_title                 	:		"WAN",
	t_wan_port              	:		"WAN Port:",
	t_wan_con_type          	:		"WAN Connection Type:",
	t_usr_name              	:		"User Name:",
	t_pwd                   	:		"Password:",
	t_dyn_ip                	:		"Dynamic IP",
	t_stat_ip               	:		"Static IP",
	t_ip_addr               	:		"IP Address:",
	t_subnet_mask           	:		"Subnet Mask:",
	t_wan_con_mod           	:		"WAN Connection Mode:",
	t_conn_on_demand        	:		"Connect on Demand",
	t_max_idle_time         	:		"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Max Idle Time: &nbsp;",
	t_mins                  	:		" minutes (0 means remain active at all times.)",
	t_con_auto              	:		"Connect Automatically",
	t_time_base             	:		"Time-based Connecting",
	t_period_time           	:		"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Period of Time:from&nbsp;",
	t_hm                    	:		"(HH:MM) to",
	t_conn_manu             	:		"Connect Manually",
	t_max_idle_time1        	:		"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Max Idle Time: &nbsp;",
	t_mins1                 	:		" minutes (0 means remain active at all times.)",
	t_disconnected          	:		"Disconnected",
	t_connected             	:		"Connected",
	t_connecting            	:		"Connecting...",
	js_bad_waittime         	:		"Wrong time format, please input another number (0-99)!",	
	js_bad_hour             	:		"Wrong time format, please input another number (0-24)!",	
	js_input_time           	:		"Please input a time!",	
	js_bad_min              	:		"Wrong time format, please input another number (0-59)!",	
	js_info_end	:"js_info_end"
},

// File Name:WlanNetworkRpm.htm
ntw_wlan_network:	{
	t_title                 	:		"Wireless Settings",
	t_ssid1						:		"SSID1:",
	t_ssid2						:		"SSID2:",
	t_ssid3						:		"SSID3:",
	t_ssid4						:		"SSID4:",
	t_Region                	:		"Region:",
	t_Albania               	:		"Albania",
	t_Algeria               	:		"Algeria",
	t_Argentina             	:		"Argentina",
	t_Armenia               	:		"Armenia",
	t_Australia             	:		"Australia",
	t_Austria               	:		"Austria",
	t_Azerbaijan            	:		"Azerbaijan",
	t_Bahrain               	:		"Bahrain",
	t_Belarus               	:		"Belarus",
	t_Belgium               	:		"Belgium",
	t_Belize                	:		"Belize",
	t_Bolivia               	:		"Bolivia",
	t_Brazil                	:		"Brazil",
	t_Brunei                	:		"Brunei Darussalam",
	t_Bulgaria              	:		"Bulgaria",
	t_Canada                	:		"Canada",
	t_Chile                 	:		"Chile",
	t_China                 	:		"China",
	t_Colombia              	:		"Colombia",
	t_Costa                 	:		"Costa Rica",
	t_Croatia               	:		"Croatia",
	t_Cyprus                	:		"Cyprus",
	t_Czech                 	:		"Czech Republic",
	t_Denmark               	:		"Denmark",
	t_Dominican             	:		"Dominican Republic",
	t_Ecuador               	:		"Ecuador",
	t_Egypt                 	:		"Egypt",
	t_El                    	:		"El Salvador",
	t_Estonia               	:		"Estonia",
	t_Finland               	:		"Finland",
	t_France                	:		"France",
	t_Georgia               	:		"Georgia",
	t_Germany               	:		"Germany",
	t_Greece                	:		"Greece",
	t_Guatemala             	:		"Guatemala",
	t_Honduras              	:		"Honduras",
	t_Hong                  	:		"Hong Kong",
	t_Hungary               	:		"Hungary",
	t_Iceland               	:		"Iceland",
	t_India                 	:		"India",
	t_Indonesia             	:		"Indonesia",
	t_Iran                  	:		"Iran",
	t_Ireland               	:		"Ireland",
	t_Israel                	:		"Israel",
	t_Italy                 	:		"Italy",
	t_Japan                 	:		"Japan",
	t_Japan1                	:		"Japan1",
	t_Japan2                	:		"Japan2",
	t_Japan3                	:		"Japan3",
	t_Japan4                	:		"Japan4",
	t_Japan5                	:		"Japan5",
	t_Japan6                	:		"Japan6",
	t_Jordan                	:		"Jordan",
	t_Kazakhstan            	:		"Kazakhstan",
	t_North                 	:		"North Korea",
	t_Korea                 	:		"Korea Republic",
	t_Korea2                	:		"Korea Republic2",
	t_Kuwait                	:		"Kuwait",
	t_Latvia                	:		"Latvia",
	t_Lebanon               	:		"Lebanon",
	t_Liechtenstein         	:		"Liechtenstein",
	t_Lithuania             	:		"Lithuania",
	t_Luxembourg            	:		"Luxembourg",
	t_Macau                 	:		"Macau",
	t_Macedonia             	:		"Macedonia",
	t_Malaysia              	:		"Malaysia",
	t_Malta                 	:		"Malta",
	t_Mexico                	:		"Mexico",
	t_Monaco                	:		"Monaco",
	t_Morocco               	:		"Morocco",
	t_Netherlands           	:		"Netherlands",
	t_New                   	:		"New Zealand",
	t_Norway                	:		"Norway",
	t_Oman                  	:		"Oman",
	t_Pakistan              	:		"Pakistan",
	t_Panama                	:		"Panama",
	t_Peru                  	:		"Peru",
	t_Philippines           	:		"Philippines",
	t_Poland                	:		"Poland",
	t_Portugal              	:		"Portugal",
	t_Puerto                	:		"Puerto Rico",
	t_Qatar                 	:		"Qatar",
	t_Romania               	:		"Romania",
	t_Russia                	:		"Russia",
	t_Saudi                 	:		"Saudi Arabia",
	t_Singapore             	:		"Singapore",
	t_Slovak                	:		"Slovak Republic",
	t_Slovenia              	:		"Slovenia",
	t_South                 	:		"South Africa",
	t_Spain                 	:		"Spain",
	t_Sweden                	:		"Sweden",
	t_Switzerland           	:		"Switzerland",
	t_Syria                 	:		"Syria",
	t_Taiwan                	:		"Taiwan",
	t_Thailand              	:		"Thailand",
	t_Trinidad              	:		"Trinidad & Tobago",
	t_Tunisia               	:		"Tunisia",
	t_Turkey                	:		"Turkey",
	t_Ukraine               	:		"Ukraine",
	t_UnitedA               	:		"United Arab Emirates",
	t_UnitedK               	:		"United Kingdom",
	t_UnitedS               	:		"United States",
	t_Uruguay               	:		"Uruguay",
	t_Uzbekistan            	:		"Uzbekistan",
	t_Venezuela             	:		"Venezuela",
	t_Viet                  	:		"Viet Nam",
	t_Yemen                 	:		"Yemen",
	t_Zimbabwe              	:		"Zimbabwe",
	t_warning               	:		"Warning:",
	t_ensure_country			:		"Ensure you select a correct country to conform local law.",
	t_cause_if	             	:		"Incorrect settings may cause interference.",
	t_channel               	:		"Channel:",
	t_Automatic             	:		"Automatic",
	t_mode                  	:		"Mode:",
	t_11b_only                  :		"11b only",
	t_11g_only                 	:		"11g only",
	t_11n_only           		:		"11n only",
	t_11bg_mix          		:		"11bg mixed",
	t_11bgn_mix					:		"11bgn mixed",
	t_enWirlessRadio           	:		"Enable Wireless Router Radio",
	t_enSsidBroadcast      		:		"Enable SSID Broadcast",
	t_enWdsbrl             		:		"Enable WDS",
	t_chn_width					:		"Channel Width:",
	t_20M						:		"20Mhz",
	t_40M						:		"40Mhz",
	t_brlssid					:		"SSID(to be bridged):",
	t_brlbssid					:		"BSSID(to be bridged):",
	t_example					:		"Example:",
	t_keytype					:		"Key type:",
	t_none						:		"None",
	t_wep_asc					:		"WEP(ASCII)",
	t_wep_hex					:		"WEP(HEX)",
	t_wpapsk					:		"WPA-PSK/WPA2-PSK",
	t_wepindex					:		"WEP Index:",
	t_authtype					:		"Auth type:",
	t_open						:		"open",
	t_shared					:		"shared",
	t_keytext					:		"Password:",
	t_chng						:		"The change of wireless config will not take effect until the Router reboots, please ",
	t_click						:		"click here",
	t_to_reboot					:		" to reboot.",
	js_input_ssid           	:		"Please input SSID!",
	js_ssid_exe					:		"The SSID cannot exceed 32 characters. Please input correctly!",
	js_input_bridge_ssid		:		"Please input Bridged SSID!",
	js_bridge_broadcast			:		"The bridged BSSID is broadcast address, please input again!",
	js_bridge_invalid			:		"The bridged BSSID is invalid, please input again!",
	js_bridge_multicast			:		"The bridged BSSID is multicast address, please input again!",
	js_ascii_keylen				:		"The ASCII key'length must be 5,13 or 16!",
	js_hex_keylen				:		"The HEX key'length must be 10,26 or 32!",
	js_wepkey_corret			:		"The hex wep key includes illegal characters!",
	js_pskkey_corret			:		"The Hex PSK key includes illegal characters!",
	js_ssid_ill					:		"The SSID contains illegal characters, please input another one!",
	js_sel_country				:		"Selecting the incorrect country may cause interference to other devices and violate the applicable law.",
	js_current_enc				:		"Current encryption is WEP,which 11n only mode can not support.If you select ok,the security setting will be lost,continue?",
	js_cur_tkip					:		"Current encryption is Automatic or TKIP,which 11n only mode can not support.If you select ok,the encryption will be changed to AES,continue?",
	js_bridge_chan_error		:		"AP channel can't be set to auto if the WDS is checked!",
	js_bridge_not_same			:		"The Bridged AP's channel is not the same as your AP's.Please reset your channel or disable the bridge function.",
	js_security_not_set			:		"Your AP's security is WEP and the index isn't 1, so you can't use the wpa_psk as WDS's security.",
	js_wep_notsame				:		"If both your AP and WDS use WEP with the same index as security mode, then you should make sure the keys are the same!",
	js_info_end	:"js_info_end"
},

// File Name:WlanSecurityRpm.htm
ntw_wlan_sec:	{
	t_title						:		"Wireless Security",
	t_currentSSID				:		"Current SSID:",
	t_disSec					:		"Disable Security",
	t_wep						:		"WEP",
	t_type						:		"Type:",
	t_auto                  	:		"Automatic",
	t_open_sys              	:		"Open System",
	t_shared_key            	:		"Shared Key",
	t_wep_key_fmt				:		"WEP Key Format:",
	t_hexadecimal           	:		"Hexadecimal",
	t_ascii                 	:		"ASCII",
	t_key_sel					:		"Key Selected",
	t_wep_key					:		"WEP Key",
	t_key_type					:		"Key Type",
	t_key                   	:		"Key ",
	t_disable	              	:		"Disabled",
	t_64bit                 	:		"64bit",
	t_128bit                	:		"128bit",
	t_152bit                	:		"152bit",
	t_wep_warn_1				:		"We do not recommend using the WEP encryption if the device operates in ",
	t_wep_warn_2				:		"802.11n mode due to the fact that WEP is not supported by 802.11n specification.",
	t_wpawpa2               	:		"WPA/WPA2",
	t_ver						:		"Version:",
	t_wpa                   	:		"WPA",
	t_wpa2                  	:		"WPA2",
	t_encrypt					:		"Encryption:",
	t_tkip                  	:		"TKIP",
	t_aes                   	:		"AES",
	t_radius_srv_ip         	:		"Radius Server IP:",
	t_radius_port           	:		"Radius Port:",
	t_rd_port_note    		   	:		"(1-65535, 0 stands for default port 1812)",
	t_radius_pwd            	:		"Radius password:",
	t_key_update_prd			:		"Group Key Update Period:",
	t_key_update_prd_note		:		"(in second, minimum is 30, 0 means no update)",
	t_tkip_warn_1				:		"We do not recommend using the TKIP encryption if the device operates in ",
	t_tkip_warn_2				:		"802.11n mode due to the fact that TKIP is not supported by 802.11n specification.",
	t_psk                   	:		"WPA-PSK/WPA2-PSK",
	t_wpa_psk               	:		"WPA-PSK",
	t_wpa2_psk              	:		"WPA2-PSK",
	t_psk_pwd               	:		"PSK Password:",
	t_psk_note					:		"(You can enter ASCII characters between 8 and 63 or Hexadecimal characters between 8 and 64.)",
	t_chng						:		"The change of wireless config will not take effect until the Router reboots, please ",
	t_click						:		"click here",
	t_to_reboot					:		" to reboot.",
	t_reboot					:		"Reboot",
	js_inv_ip					:		"Invalid IP address for Radius Server, please input again!",
	js_enpty_radius				:		"Please input Radius password!",
	js_radius_password			:		"Radius password must be less than 64 characters, please input again!",
	js_radius_port				:		"Invalid Radius port, please input again!",	
	js_inv_update_period		:		"Invalid Group Key Update Period, please input again!",
	js_empty_psk_password		:		"Empty PSK password, please input one!",
	js_psk_char					:		"PSK password should not be less than 8 characters, please input again!",
	js_psk_hex					:		"The 64 bytes PSK password include non-hexadecimal characters, please input again.",
	js_no_wep_key				:		"The WEP key is empty, are you sure to continue?",
	js_wep_key_inv_hex			:		"WEP key is invalid!\nThe WEP Key Format is Hexadecimal currently.\nMake sure that all digits are Hexadecimal (zero key is illegal) and the length meets the requirement.",
	js_wep_key_inv_asc			:		"WEP key is invalid!\nThe WEP Key Format is ASCII currently.\nMake sure that all characters are ASCII (not including any other character) and the length meets the requirement.",
	js_ill_chars				:		"The password value contain illegal characters, please input another one!",
	js_sec_error_set			:		"Your WDS's security is WPA-PSK. So if your AP's security is WEP, The index should be 1!",
	js_sec_wep_notsame			:		"If both your AP and WDS use WEP with the same index as security mode, then you should make sure the keys are the same!",
	js_router_reboot			:		"The change of wireless config will not take effect until the Router reboot.",
	js_info_end	:"js_info_end"
},

// File Name:WlanWpsRpm.htm
ntw_wlan_wps:	{
	t_title                 	:		"WPS (Wi-Fi Protected Setup)",
	t_currentSSID				:		"Current SSID:",
	t_allow						:		"You should turn on wireless first,",
	t_click_here				:		" Click here ",
	t_enb_radio					:		"to Enable Wireless Router Radio.",
	t_status					:		"WPS Status:",
	t_disabled					:		"Disabled",
	t_enabled					:		"Enabled",
	t_cur_pin					:		"Current PIN:",
	t_add_dev					:		"Add a new device:",
	t_chng						:		"The change of wireless config will not take effect until the Router reboots, please",
	t_to_reboot					:		"to reboot.",
	js_info_end	:"js_info_end"
},

// File Name:WlanWpsChkModeRpm.htm
ntw_wlan_chk_mode:	{
	t_title                 	:		"Add A New Device",
	t_dev_pin					:		"Enter the new device's PIN.",
	t_pin						:		"PIN:",
	t_new_dev_pin				:		"Press the button of the new device in two minutes.",
	t_wrong_pin					:		"Invalid WPS PIN, please check if it is correct!",
	t_conneting					:		"Connecting ...",
	t_con_suc					:		"Connect successfully!",
	t_con_err					:		"Connect error!",
	js_pin_dig					:		"The PIN must be a 8-digit number.",
	js_illegal_input			:		"The input value contain illegal characters, please input another one!",
	js_info_end	:"js_info_end"
},

// File Name:WlanWpsRpm.htm
ntw_wlan_adv:	{
	t_title                 	:		"Wireless Advanced",
	t_transmit_power			:		"Transmit Power:",
	t_high						:		"High",
	t_middle					:		"Middle",
	t_low						:		"Low",
	t_beacon_interval			:		"Beacon Interval:",
	t_beacon_interval_note		:		"(40-1000)",
	t_rts_threshold				:		"RTS Threshold:",
	t_rts_threshold_note		:		"(1-2346)",
	t_frag						:		"Fragmentation Threshold:",
	t_frag_note					:		"(256-2346)",
	t_dtim						:		"DTIM Interval:",
	t_dtim_note					:		"(1-255)",
	t_enable_wmm				:		"Enable WMM",
	t_enable_short_gi			:		"Enable Short GI",
	t_enable_ap					:		"Enable AP Isolation",
	t_chng						:		"The change of wireless config will not take effect until the Router reboots, please",
	t_click						:		" click here ",
	t_to_reboot					:		"to reboot.",
	js_pl_sel_power				:		"Please select the correct transmit power!",
	js_beacon					:		"The value of Beacon Interval should be between 40 and 1000, please input a correct one!",
	js_rts						:		"The value of RTS Threshold should be between 1 and 2346, please input a correct one!",
	js_frag						:		"The value of Fragmentation Threshold should be between 256 and 2346, please input a correct one!",
	js_dtim						:		"The value of DTIM Interval should be between 1 and 255, please input a correct one!",
	js_info_end	:"js_info_end"
},

// File Name:WzdWlanRpm.htm
ntw_wzd_wlan:	{
	t_title                 	:		"Quick Setup - Wireless",
	t_item                  	:		"Please config parameters of AP Mode:",
	t_radio                 	:		"Wireless Radio:",
	t_disable               	:		"Disable",
	t_enable                	:		"Enable",
	t_ssid                  	:		"SSID:",
	t_region                	:		"Region:",
	t_Albania               	:		"Albania",
	t_Algeria               	:		"Algeria",
	t_Argentina             	:		"Argentina",
	t_Armenia               	:		"Armenia",
	t_Australia             	:		"Australia",
	t_Austria               	:		"Austria",
	t_Azerbaijan            	:		"Azerbaijan",
	t_Bahrain               	:		"Bahrain",
	t_Belarus               	:		"Belarus",
	t_Belgium               	:		"Belgium",
	t_Belize                	:		"Belize",
	t_Bolivia               	:		"Bolivia",
	t_Brazil                	:		"Brazil",
	t_Brunei                	:		"Brunei Darussalam",
	t_Bulgaria              	:		"Bulgaria",
	t_Canada                	:		"Canada",
	t_Chile                 	:		"Chile",
	t_China                 	:		"China",
	t_Colombia              	:		"Colombia",
	t_Costa                 	:		"Costa Rica",
	t_Croatia               	:		"Croatia",
	t_Cyprus                	:		"Cyprus",
	t_Czech                 	:		"Czech Republic",
	t_Denmark               	:		"Denmark",
	t_Dominican             	:		"Dominican Republic",
	t_Ecuador               	:		"Ecuador",
	t_Egypt                 	:		"Egypt",
	t_El                    	:		"El Salvador",
	t_Estonia               	:		"Estonia",
	t_Finland               	:		"Finland",
	t_France                	:		"France",
	t_Georgia               	:		"Georgia",
	t_Germany               	:		"Germany",
	t_Greece                	:		"Greece",
	t_Guatemala             	:		"Guatemala",
	t_Honduras              	:		"Honduras",
	t_Hong                  	:		"Hong Kong",
	t_Hungary               	:		"Hungary",
	t_Iceland               	:		"Iceland",
	t_India                 	:		"India",
	t_Indonesia             	:		"Indonesia",
	t_Iran                  	:		"Iran",
	t_Ireland               	:		"Ireland",
	t_Israel                	:		"Israel",
	t_Italy                 	:		"Italy",
	t_Japan                 	:		"Japan",
	t_Japan1                	:		"Japan1",
	t_Japan2                	:		"Japan2",
	t_Japan3                	:		"Japan3",
	t_Japan4                	:		"Japan4",
	t_Japan5                	:		"Japan5",
	t_Japan6                	:		"Japan6",
	t_Jordan                	:		"Jordan",
	t_Kazakhstan            	:		"Kazakhstan",
	t_North                 	:		"North Korea",
	t_Korea                 	:		"Korea Republic",
	t_Korea2                	:		"Korea Republic2",
	t_Kuwait                	:		"Kuwait",
	t_Latvia                	:		"Latvia",
	t_Lebanon               	:		"Lebanon",
	t_Liechtenstein         	:		"Liechtenstein",
	t_Lithuania             	:		"Lithuania",
	t_Luxembourg            	:		"Luxembourg",
	t_Macau                 	:		"Macau",
	t_Macedonia             	:		"Macedonia",
	t_Malaysia              	:		"Malaysia",
	t_Malta                 	:		"Malta",
	t_Mexico                	:		"Mexico",
	t_Monaco                	:		"Monaco",
	t_Morocco               	:		"Morocco",
	t_Netherlands           	:		"Netherlands",
	t_New                   	:		"New Zealand",
	t_Norway                	:		"Norway",
	t_Oman                  	:		"Oman",
	t_Pakistan              	:		"Pakistan",
	t_Panama                	:		"Panama",
	t_Peru                  	:		"Peru",
	t_Philippines           	:		"Philippines",
	t_Poland                	:		"Poland",
	t_Portugal              	:		"Portugal",
	t_Puerto                	:		"Puerto Rico",
	t_Qatar                 	:		"Qatar",
	t_Romania               	:		"Romania",
	t_Russia                	:		"Russia",
	t_Saudi                 	:		"Saudi Arabia",
	t_Singapore             	:		"Singapore",
	t_Slovak                	:		"Slovak Republic",
	t_Slovenia              	:		"Slovenia",
	t_South                 	:		"South Africa",
	t_Spain                 	:		"Spain",
	t_Sweden                	:		"Sweden",
	t_Switzerland           	:		"Switzerland",
	t_Syria                 	:		"Syria",
	t_Taiwan                	:		"Taiwan",
	t_Thailand              	:		"Thailand",
	t_Trinidad              	:		"Trinidad & Tobago",
	t_Tunisia               	:		"Tunisia",
	t_Turkey                	:		"Turkey",
	t_Ukraine               	:		"Ukraine",
	t_UnitedA               	:		"United Arab Emirates",
	t_UnitedK               	:		"United Kingdom",
	t_UnitedS               	:		"United States",
	t_Uruguay               	:		"Uruguay",
	t_Uzbekistan            	:		"Uzbekistan",
	t_Venezuela             	:		"Venezuela",
	t_Viet                  	:		"Viet Nam",
	t_Yemen                 	:		"Yemen",
	t_Zimbabwe              	:		"Zimbabwe",
	t_channel               	:		"Channel:",
	t_Automatic             	:		"Automatic",
	t_mode                  	:		"Mode:",
	t_11b_only                  :		"11b only",
	t_11g_only                 	:		"11g only",
	t_11n_only           		:		"11n only",
	t_11bg_mix          		:		"11bg mixed",
	t_11bgn_mix					:		"11bgn mixed",
	t_channel_wd				:		"Channel Width:",
	t_auto						:		"Auto",
	t_20M						:		"20Mhz",
	t_40M						:		"40Mhz",
	t_enb_ssid_bc				:		"Enable SSID Broadcast:",
	t_wireless_sec				:		"Wireless Security:",
	t_disSec					:		"Disable Security",
	t_wpapsk					:		"WPA-PSK/WPA2-PSK",
	t_psk_pwd					:		"PSK Password:",
	t_psk_note					:		"(You can enter ASCII characters between 8 and 63 or Hexadecimal characters between 8 and 64.)",
	t_no_change					:		"No Change",
	js_pl_ssid					:		"Please input SSID!",
	js_ssid_exc_alp				:		"The SSID cannot exceed 32 alphanumeric characters. Please input correctly!",
	js_cur_exc_wep				:		"Current encryption is WEP,11n only mode is not support,if you select ok,the security setting will be loss,continue?",
	js_cur_enc_auto				:		"Current encryption is Automatic or TKIP,11n only mode is not support for TKIP,if you select ok,the encryption will be changed to AES,continue?",
	js_empty_psk_password		:		"Empty PSK password, please input one!",
	js_psk_char					:		"PSK password should not be less than 8 characters, please input again!",
	js_psk_too_long				:		"PSK password should not be longer than 64 characters, please input again!",
	js_psk_hex					:		"The 64 bytes PSK password include non-hexadecimal characters, please input again.",
	js_illegal_passwd			:		"The password value contain illegal characters, please input another one!",	
	js_info_end	:"js_info_end"
},

// File Name:StatusRpm.htm
ntw_status:	{
	t_dyn_ip                	:		"Dynamic IP",
	t_static_ip             	:		"Static IP",
	t_ie_dyn                	:		"IEEE802.1X + Dynamic IP",
	t_ie_static             	:		"IEEE802.1X + Static IP",
	t_big_pond_cable        	:		"Big Pond Cable",
	t_l2tp                  	:		"L2TP/Russia L2TP",
	t_pptp                  	:		"PPTP/Russia PPTP",
	t_dualaccess            	:		"Dual Access/Russia PPPOE",
	t_disabled              	:		"Disabled",
	t_timeout               	:		"Timeout",
	t_link_down             	:		"Link Down",
	t_link_up               	:		"Link Up",
	t_sta                   	:		"108Mbps (Static)",
	t_dyn                   	:		"108Mbps (Dynamic)",
	t_not_log_in            	:		"Not log in",
	t_logging_in            	:		"Logging in, please wait...",
	t_longin_successfully   	:		"Login successfully",
	t_obtaining_net_paramenter	:		"Obtaining network parameters...",
	t_disconnected          	:		"Wan is disconnected!",
	t_title                 	:		"Status",
	t_firm_vs               	:		"Firmware Version:",
	t_hd_vs                 	:		"Hardware Version:",
	t_lan                   	:		"LAN",
	t_wired                 	:		"Wired",
	t_mac_addr              	:		"MAC Address:",
	t_ip_addr               	:		"IP Address:",
	t_sub_mask              	:		"Subnet Mask:",
	t_node_disable          	:		"Disabled",
	t_acc_point             	:		"Access Point",
	t_client1               	:		"Client",
	t_client2               	:		"Client",
	t_repeater              	:		"Repeater",
	t_unRepeater            	:		"Universal Repeater",
	t_bridge_p2p            	:		"Bridge (Point to Point)",
	t_bridge_p2m            	:		"Bridge (Point to Multi-Point)",
	t_disable               	:		"Disable",
	t_enable                	:		"Enable",
	t_wireless              	:		"Wireless",
	t_mode1                 	:		"Operating Mode:",
	t_wireless_radio        	:		"Wireless Radio:",
	t_signal                	:		"Signal:",
	t_remoteMAC             	:		"Remote MAC:",
	t_channel               	:		"Channel:",
	t_auto                  	:		"Automatic",
	t_mode                  	:		"Mode:",
	t_mac_addr2             	:		"MAC Address:",
	t_ip_addr2              	:		"IP Address:",
	t_wan1                  	:		"WAN",
	t_status                	:		"Status:",
	t_mac_addr1             	:		"MAC Address:",
	t_ip_addr1              	:		"IP Address:",
	t_sub_mask1             	:		"Subnet Mask:",
	t_def_gt                	:		"Default Gateway:",
	t_ddns_ser              	:		"DNS Server:",
	t_online_time           	:		"Online Time:",
	t_days                  	:		"&nbsp;day(s)",
	t_connecting            	:		"Connecting...",
	t_trff_stat             	:		"Traffic Statistics",
	t_received              	:		"Received",
	t_sent                  	:		"Sent",
	t_byt                   	:		"Bytes:",
	t_pcks                  	:		"Packets:",
	t_rate                  	:		"Rate",
	t_rece_byt              	:		"Received (Bytes)",
	t_rece_pck              	:		"Received (Packets)",
	t_sent_pcks             	:		"Sent (Packets)",
	t_total                 	:		"Total",
	t_sys_up_time           	:		"System Up Time:",
	t_day                   	:		" day(s) ",
	js_info_end	:"js_info_end"
},

// File Name:common.js
ntw_common_js:	{
	js_input_ip0            	:		"Please input an IP address(1-254)!",	
	js_bad_ip0              	:		"The IP address is invalid, please input another one(1-254)!",	
	js_input_ip1            	:		"Please input an IP address!",	
	js_bad_ip1              	:		"The IP address is invalid, please input another one!",	
	js_input_gateway        	:		"Please input the Gateway!",	
	js_bad_gateway          	:		"The gateway is invalid, please input another one!",	
	js_input_dns            	:		"Please input the DNS server address (for example 202.96.134.133)!",	
	js_bad_dns              	:		"The DNS server address is invalid, please input another one(for example 202.96.134.133)!",	
	js_illegal_input        	:		"The input value contain illegal characters, please input another one!",	
	js_input_port           	:		"Please input the port number (1-65534)!",	
	js_bad_port             	:		"The port number is invalid, please input another one(1-65534)!",	
	js_input_mask           	:		"Please input the Subnet Mask (for example: 255.255.255.0)!",	
	js_bad_mask             	:		"The Subnet Mask is invalid, please input another one (for example: 255.255.255.0)!",	
	js_bad_mac_format       	:		"The MAC address format is invalid! The valid format is '00-00-00-00-00-00'.",	
	js_inv_mac_zero         	:		"Invalid MAC address, please input again!",	
	js_invalid_mac          	:		"Invalid MAC address, please input another one!",	
	js_broadcast_mac        	:		"The MAC address is a broadcast MAC address, please input again!",	
	js_multi_mac            	:		"The MAC address is a multicast MAC address, please input again!",	
	js_input_mac            	:		"Please input a MAC address!",	
	js_input_msg            	:		"You can input up to 30 characters, please input again!",	
	js_input_too_many       	:		"You input too many characters, please input again!",	
	js_info_end	:"js_info_end"
},
obj_end	:	""
}
var str_main = new Array();
str_main.charset = "text/html; charset=gb2312"
str_main.btn = {
Save                    	:	"Save",
Showhostlist            	:	"Blocked Dos Host List",
Refresh                 	:	"Refresh",
Backup                  	:	"Backup",
Restore                 	:	"Restore",
Connect                 	:	"Connect",
Disconnect              	:	"Disconnect",
Clear                   	:	"Clear All",
Login                   	:	"Login",
Logout                  	:	"Logout",
Return                  	:	"Back",
Gettime                 	:	"Get GMT",
Addnew                  	:	"Add New...",
Enall                   	:	"Enable All",
Disall                  	:	"Disable All",
Delall                  	:	"Delete All",
Previous                	:	"Previous",
Next                    	:	"Next",
Sub                     	:	"Start",
Find                    	:	"Find",
Capture                 	:	"Bind All",
Resall                  	:	"Load All",
RestoreMAC              	:	"Restore Factory MAC",
CloneMAC                	:	"Clone MAC Address To",
Advanced                	:	"Advanced",
Restorefactory          	:	"Restore",
Upgrade                 	:	"Upgrade",
Reboot                  	:	"Reboot",
Clearlog                	:	"Clear All",
Staton                  	:	"Enable",
Statoff                 	:	"Disable",
Resetall                	:	"Reset All",
Upnpdisable             	:	"Disable",
Upnpenable              	:	"Enable",
RenewIP                 	:	"Renew",
ReleaseIP               	:	"Release",
Move                    	:	"Move",
Enable                  	:	"Enable",
Disable                 	:	"Disable",
Secwzd                  	:	"Firewall Cfg",
Finish                  	:	"Finish",
Exit                    	:	"Exit",
EnWps						:	"Enable WPS",
DisWps						:	"Disable WPS",
Survey						:	"Survey",
end_button					:	"end_button"
}